name: docblog
on:
  schedule:
  - cron: "*/5 * * * *" # At every 5th minute
jobs:
  docblog:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout jupblb/docblog
      uses: actions/checkout@v4
      with:
        repository: jupblb/docblog
        path: docblog
    - name: Checkout jupblb/jupblb.github.io (website)
      uses: actions/checkout@v4
      with:
        repository: jupblb/jupblb.github.io
        path: website
        token: ${{ secrets.PAT }}
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - id: gcloud_auth
      uses: google-github-actions/auth@v2
      with:
        project_id: docblog-424619
        credentials_json: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }}
    - uses: google-github-actions/setup-gcloud@v2
    - name: 'Clear website'
      run: |
        cd "$GITHUB_WORKSPACE/website"
        rm -f _posts/*.html
    - name: 'Run docblog'
      run: |
        cd "$GITHUB_WORKSPACE/docblog"
        go run cmd/docblog/main.go \
          --gemini-api-key ${{ secrets.GEMINI_API_KEY }} \
          --assets-output ../website/ \
          --assets-prefix assets \
          --credentials ${{ steps.gcloud_auth.outputs.credentials_file_path }} \
          --posts-output ../website/_posts \
          ${{ vars.GOOGLE_DRIVE_ID }}
    - name: 'Format HTML posts'
      uses: creyD/prettier_action@v4.3
      with:
        prettier_options: --write ${{ github.workspace }}/website/_posts/*.html
    # https://stackoverflow.com/a/58393457/2900417
    - name: 'Update website'
      run: |
        cd "$GITHUB_WORKSPACE/website"
        git config --global user.name 'Michal Kielbowicz'
        git config --global user.email 'jupblb@users.noreply.github.com'
        git add .
        git commit -m "$(date)"
        git push
